// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjfckjkklinmmdentwxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqZmNramtrbGlubW1kZW50d3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODk4ODQsImV4cCI6MjA3MjY2NTg4NH0.C6N8rTPL6QAWc9n-9JHe192N6Eb_T-jnpqesm9U9st4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});